---
- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade OS
  apt: upgrade=dist force=yes

- name: Install Java (>=7)
  apt: name="{{ item }}" state=latest
  with_items:
    - default-jre
    - default-jdk
    - git
    - lib32stdc++6
    - lib32z1


  