---
# Fetch appropriate dependencies

- include: debian_repo.yml
  when: ansible_os_family == "Debian"

- include: redhat_repo.yml
  when: ansible_os_family == "RedHat"

- name: Check if pip is installed
  command: bash -c "pip --version | grep pip"
  register: pip_version
  ignore_errors: True
  tags:
    - common

- name: Download pip if not present
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ ansible_env.PWD }}
  when: pip_version|failed
  tags:
    - common

- name: Install downloaded pip file
  command: python get-pip.py
  args:
    chdir: "{{ ansible_env.PWD}}"
  when: pip_version|failed
  tags:
    - common

- name: Check if Pexpect is installed
  command: bash -c "pip list --format legacy | grep pexpect | grep -Eo '[0-9.]{1,}'"
  register: pexpect_version
  ignore_errors: True
  tags:
    - common

- name: Install Pexpect
  pip: name=pexpect state=latest
  when: pexpect_version.stdout < '3.3'
  tags:
    - common

# Install appropriate dependencies

- include: debian_dependencies.yml
  when: ansible_os_family == "Debian"

- include: redhat_dependencies.yml
  when: ansible_os_family == "RedHat"
  