---
- name: Add Java apt repository
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade OS
  apt: upgrade=dist force=yes

- name: Install Java (>=7)
  apt: name="{{ item }}" state=latest
    with_items:
      - oracle-java8-installer
      - git
      - lib32stdc++6
      - lib32z1


  