---
- name: Check config directory for Android SDK artifacts
  command: bash -c "cd {{ android_home_directory }}"
  register: android_home_exists
  ignore_errors: True
  tags:
    - sdk_download
    - sdk_update

- name: Check for platform directory inside ANDROID HOME directory
  command: bash -c "ls {{ android_home_directory }} | grep platform"
  register: platform_found
  when: android_home_exists|success
  ignore_errors: True
  tags:
    - sdk_download
    - sdk_update

- name: Create ANDROID HOME directory
  file: path={{ android_home_directory }} state=directory mode=0777
  when: android_home_exists|failed
  tags:
    - sdk_download

- name: Download Android SDK Tools
  get_url: url=https://dl.google.com/android/repository/tools_r{{ sdk_tools_version }}-linux.zip dest={{ android_home_directory }}
  when: android_home_exists|failed or platform_found|failed
  tags:
    - sdk_download

- name: Unarchive Android SDK Tools
  unarchive: src={{ android_home_directory }}/tools_r{{ sdk_tools_version }}-linux.zip dest={{ android_home_directory }} copy=no
  when: android_home_exists|failed or platform_found|failed
  tags:
    - sdk_download

- name: Verify that SDK Tools have been downloaded
  command: bash -c "ls {{ android_home_directory }} | grep tools"
  when: android_home_exists|failed or platform_found|failed
  tags:
    - sdk_download

- name: Download packages and move them to ANDROID HOME directory
  command: bash -c "echo y | ./android update sdk --no-ui --filter platform,platform-tools" chdir={{ android_home_directory }}/tools
  when: android_home_exists|failed or platform_found|failed
  tags:
    - sdk_update

- name: Delete downloaded tools archive
  file: path={{ android_home_directory }}/*linux.zip state=absent
  when: android_home_exists|failed or platform_found|failed
  tags:
    - sdk_update

- name: Check if android.sh exists in /etc/profile.d directory
  command: bash -c "ls /etc/profile.d/ | grep android.sh"
  register: android_profile_found
  ignore_errors: True
  tags:
    - sdk_configure

- name: Create android.sh file in /etc/profile.d/ directory
  template: src=android.sh dest=/etc/profile.d/
  when: android_profile_found|failed
  tags:
    - sdk_configure

- name: 1. Reload /etc/profile.d directory 2. Download android build tools 3. Restart server
  command: bash -c "{{ item }}" chdir={{ android_home_directory }}/tools
  with_items:
    - source /etc/profile
    - echo y | ./android update sdk -u --all --filter build-tools-{{ build_tools_version }}
  when: android_profile_found|failed
  tags:
    - sdk_configure

- name: Verify that ANDROID_HOME is added to environment variables
  command: bash -c "{{ item }}"
  with_items:
    - cat /etc/profile.d/android.sh | grep ANDROID_HOME
    - shutdown -r now
  tags:
    - sdk_configure
