---
- name: Update SDK with Google API ABI
  command: bash -c "echo y | ./android update sdk -u -a -t {{ avd_android_version }},{{ google_api_system_image }}"
  when: create_avd
  tags:
    - avd_configure

- name: Create AVD
  command: bash -c "echo no | ./android create avd --force -n {{ avd_name }} -t {{ avd_android_version }} --abi armeabi-v7a" chdir={{ android_home_directory }}/tools
  when: create_avd
  tags:
    - avd_configure

- name: Check that created avd is shown in list of devices
  command: bash -c "./android list avd | grep {{ avd_name }}"
  tags:
    - avd_verify

