# Configurable variables for all playbooks
hosts: vagrant
user: vagrant

# Configuration for Android SDK
sdk_tools_version: 25.2.3

android_home_directory: /opt/android-sdk-linux
build_tools_version: 25.0.2