# Configurable variables for all playbooks
hosts: vagrant
user: vagrant

# Configuration for Android SDK
sdk_tools_version: 25.2.3

android_home_directory: /opt/android-sdk-linux
build_tools_version: 25.0.2

# Option to create AVD. Please set to false in subsequent executions
create_avd: true
avd_name: Lollipop
avd_android_version: android-22
google_api_system_image: sys-img-armeabi-v7a-google_apis-22
abi_version: 


# Note that there's currently only support for armeabi-v7a
# So make sure the avd version has an ABI for armeabi-v7a
