# Configurable variables for all playbooks
hosts: labserver
user: kamiye

java8_rpm: jdk-8u121-linux-x64.rpm
java8_rpm_download_url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/{{ java8_rpm }}

# Configuration for Android SDK
sdk_tools_version: 25.2.3

android_home_directory: /opt/android-sdk-linux
build_tools_version: 25.0.2

# Option to create AVD. Please set to false in subsequent executions
create_avd: true
avd_name: Lollipop
avd_android_version: android-22
google_api_system_image: sys-img-armeabi-v7a-google_apis-22
abi_version: google_apis/armeabi-v7a


# Note that there's currently only support for armeabi-v7a
# So make sure the avd version has an ABI for armeabi-v7a
